language: r
cache: packages
dist: trusty
r: 
  - release
  - oldrel
  - devel
before_install:
  - sudo R CMD javareconf
  - Rscript -e 'install.packages("rJava", type = "source")'
after_success:
  - Rscript -e 'covr::codecov()'
sudo: false

matrix:
     include:
         - os: osx
           fortran: false

warnings_are_errors: true
