language: r
#cache: packages
dist: trusty
r: release
before_install:
  - sudo R CMD javareconf
  - Rscript -e 'install.packages("rJava", type = "source")'
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
sudo: false
#matrix:
#  allow_failures:
#    - os: osx
os:
  - linux
  - osx
fortran:false
warnings_are_errors: true
