language: r
cache: packages
before_install:
  - Rscript -e 'install.packages("rJava")'
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
sudo: false
os:
  - osx
warnings_are_errors: true
