language: r
#cache: packages
dist: trusty
r: release
addons:
  apt:
    packages: ['gfortran = false']
before_install:
  - sudo R CMD javareconf
  - Rscript -e 'install.packages("rJava", type = "source")'
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
sudo: false
os:
  - osx
warnings_are_errors: true
