language: r
sudo: required
cache:
  - packages
  - github_packages
r: 
    - release
    - oldrel
    - devel
r_packages:
    - devtools
    - covr
    - rcmdcheck
matrix:
     include:
         - os: osx
           fortran: false
before_install:
    - tlmgr install texlive-latex-extra --repository https://mirrors.rit.edu/CTAN/
#   - Rscript -e 'install.packages("rJava", type = "source")'
script:
  - R CMD build . 
  - R CMD check *.tar.gz --as-cran
after_success:
  - R -e CODECOV_TOKEN 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
