comment: false
codecov:
  token: 06bf0eb4-6204-484b-8806-8352bc64a435

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
